# __FINAL PROJECT PHASE II__

In [ ]:
import pandas as pd
import duckdb

In [7]:
flights_2022=pd.read_csv('Combined_Flights_2022.csv')
airports = pd.read_csv('airports.csv')

In [8]:
flights_2022.head()

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,...,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
0,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",GJT,DEN,False,False,1133,1123.0,0.0,-10.0,...,1140.0,1220.0,8.0,1245,-17.0,0.0,-2.0,1200-1259,1,0
1,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",HRL,IAH,False,False,732,728.0,0.0,-4.0,...,744.0,839.0,9.0,849,-1.0,0.0,-1.0,0800-0859,2,0
2,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1529,1514.0,0.0,-15.0,...,1535.0,1622.0,14.0,1639,-3.0,0.0,-1.0,1600-1659,2,0
3,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",IAH,GPT,False,False,1435,1430.0,0.0,-5.0,...,1446.0,1543.0,4.0,1605,-18.0,0.0,-2.0,1600-1659,2,0
4,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1135,1135.0,0.0,0.0,...,1154.0,1243.0,8.0,1245,6.0,0.0,0.0,1200-1259,2,0

In [9]:
airports.head()

,IATA,AIRPORT,CITY,STATE,COUNTRY,LATITUDE,LONGITUDE
0,ABQ,Albuquerque International,Albuquerque,NM,USA,35.040222,-106.609194
1,ANC,Ted Stevens Anchorage International,Anchorage,AK,USA,61.174320,-149.996186
2,ATL,William B Hartsfield-Atlanta Intl,Atlanta,GA,USA,33.640444,-84.426944
3,AUS,Austin-Bergstrom International,Austin,TX,USA,30.194533,-97.669872
4,BDL,Bradley International,Windsor Locks,CT,USA,41.938874,-72.683228

In [10]:
df = duckdb.sql('''
SELECT flights_2022.*
, airports.city AS origin_city
, airports.state AS origin_state
, airports.country AS origin_country
, airports.latitude AS origin_latitude
, airports.longitude AS origin_longitude
FROM flights_2022 
LEFT JOIN airports ON flights_2022.origin = airports.IATA
''').df()

In [14]:
df2 = duckdb.sql('''
SELECT df.*
, airports.city AS dest_city
, airports.state AS dest_state
, airports.country AS dest_country
, airports.latitude AS dest_latitude
, airports.longitude AS dest_longitude
FROM df
LEFT JOIN airports ON df.dest = airports.IATA
''').df()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

In [15]:
df2.head()

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,...,origin_city,origin_state,origin_country,origin_latitude,origin_longitude,dest_city,dest_state,dest_country,dest_latitude,dest_longitude
0,2022-03-06,Southwest Airlines Co.,LAS,DAL,False,False,525,524.0,0.0,-1.0,...,Las Vegas,NV,USA,36.080361,-115.152333,Dallas,TX,USA,32.847114,-96.851772
1,2022-03-06,Southwest Airlines Co.,LAS,DAL,False,False,1510,1519.0,9.0,9.0,...,Las Vegas,NV,USA,36.080361,-115.152333,Dallas,TX,USA,32.847114,-96.851772
2,2022-03-06,Southwest Airlines Co.,LAS,DAL,False,False,1155,1203.0,8.0,8.0,...,Las Vegas,NV,USA,36.080361,-115.152333,Dallas,TX,USA,32.847114,-96.851772
3,2022-03-06,Southwest Airlines Co.,LAS,DAL,False,False,1850,1902.0,12.0,12.0,...,Las Vegas,NV,USA,36.080361,-115.152333,Dallas,TX,USA,32.847114,-96.851772
4,2022-03-06,Southwest Airlines Co.,LAS,DSM,False,False,1235,1234.0,0.0,-1.0,...,Las Vegas,NV,USA,36.080361,-115.152333,Des Moines,IA,USA,41.534933,-93.660682